title: blug
description: "Cybersecurity and competitive programming"
baseurl: /
homepage: https://robertchen.cc/
markdown:         redcarpet
highlighter:      pygments
permalink:        pretty
paginate:         5
github: https://github.com/chen-robert
